### ISSUE TITLE
requirements.txt file

### ISSUE THREAD

**Issue by alonisser** [ronreiter/anyway#2]
you should add requirements.txt file so we can install the project..

**Comment by ronreiter** [comment]
it's a Google App Engine project. No need.

On Wed, Sep 18, 2013 at 3:59 PM, Alonisser notifications@github.com wrote:

> you should add requirements.txt file so we can install the project..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ronreiter/anyway/issues/2
> .

## 

Ron Reiter
[image: Facebook] http://www.facebook.com/ron.reiter [image:
Twitter]http://twitter.com/#!/ronreiter [image:
LinkedIn]http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro
Contact me: [image: Skype] ron.reiter

**Comment by ronreiter** [comment]
Maybe we should move to MySQL and Heroku because it's better to use an SQL server for this type of application.
