### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by alonisser** [ronreiter/anyway#3]
every open source project should have a license

**Comment by ronreiter** [comment]
Which one do you think we should put?

On Wed, Sep 18, 2013 at 4:00 PM, Alonisser notifications@github.com wrote:

> every open source project should have a license
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ronreiter/anyway/issues/3
> .

## 

Ron Reiter
[image: Facebook] http://www.facebook.com/ron.reiter [image:
Twitter]http://twitter.com/#!/ronreiter [image:
LinkedIn]http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro
Contact me: [image: Skype] ron.reiter

**Comment by alonisser** [comment]
Most hasadna projects use BSD 3 clause (look at [this](https://groups.google.com/forum/#!topic/hasadna11/XqFAw3a__Mc) recent discussion)

**Comment by ronreiter** [comment]
can you send a pull request?

On Wed, Sep 18, 2013 at 5:05 PM, Alonisser notifications@github.com wrote:

> Most hasadna projects use BSD 3 clause (look at thishttps://groups.google.com/forum/#!topic/hasadna11/XqFAw3a__Mcrecent discussion)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ronreiter/anyway/issues/3#issuecomment-24666266
> .

## 

Ron Reiter
[image: Facebook] http://www.facebook.com/ron.reiter [image:
Twitter]http://twitter.com/#!/ronreiter [image:
LinkedIn]http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro
Contact me: [image: Skype] ron.reiter

**Comment by ronreiter** [comment]
done
