### ISSUE TITLE
Change layers names and function

### ISSUE THREAD

**Issue by galraij** [ronreiter/anyway#4]
On right side layer list:

Layer #1:
Instead of הצעות חוק should appear תאונות
Function- turn on and off accidents markers on the map.

Layer #2:
Instead of עצומות should appear קריאה לפעולה
Function- turn on and off user added markers

**Comment by BrkCoder** [comment]
Hey,These are the changes which need to be address in this week?

**Comment by galraij** [comment]
Let's wait until Monday and see priorities. Thanks

**Comment by ronreiter** [comment]
Barak, you can start working if you want. call me

On Wed, Oct 9, 2013 at 11:39 PM, galraij notifications@github.com wrote:

> Let's wait until Monday and see priorities. Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ronreiter/anyway/issues/4#issuecomment-26006535
> .

## 

Ron Reiter
[image: Facebook] http://www.facebook.com/ron.reiter [image:
Twitter]http://twitter.com/#!/ronreiter [image:
LinkedIn]http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro
Contact me: [image: Skype] ron.reiter

**Comment by BrkCoder** [comment]
ok I got your message. :)

On Wed, Oct 9, 2013 at 10:50 PM, Ron Reiter notifications@github.comwrote:

> Barak, you can start working if you want. call me
> 
> On Wed, Oct 9, 2013 at 11:39 PM, galraij notifications@github.com
> wrote:
> 
> > Let's wait until Monday and see priorities. Thanks
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ronreiter/anyway/issues/4#issuecomment-26006535>
> > .
> 
> ## 
> 
> Ron Reiter
> [image: Facebook] http://www.facebook.com/ron.reiter [image:
> Twitter]http://twitter.com/#!/ronreiter [image:
> LinkedIn]<
> http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro>
> Contact me: [image: Skype] ron.reiter
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ronreiter/anyway/issues/4#issuecomment-26007502
> .

## 

barak inbal
Computer Science Engineer
:)(:
